Pcar =['./images/Learning Web Design.jpg',
  './images/HTML and CSS QuickStart Guide.jpg',
  './images/Head First HTML and CSS.jpg',
  './images/Learn CSS in One Day and Learn It Well.jpg',
  './images/Responsive Web Design with HTML5 and CSS.jpg',
  './images/JavaScript The Definitive Guide.jpg',
  './images/Eloquent JavaScript.jpg',
  './images/Head First HTML and CSS.jpg',
  './images/Learn JavaScript Quickly.jpg',
  './images/JJavascript for Beginners.jpg',
  './images/HTML5 for Masterminds.jpg',
  './images/HTML5 and CSS3 All-in-One For Dummies.jpg',
  './images/HTML5 Pocket Reference.jpg',
  './images/CSS  The Definitive Guide.jpg',
  './images/Python Crash Course.jpg',
  './images/Hands-On Machine Learning with Scikit-Learn.jpg',
  './images/Python for Everybody.jpg',
  './images/Build Your Own AI Investor.jpg',
  './images/Learn Python Quickly.jpg',
  './images/Head First Design Patternsn.jpg',
  './images/Elements of Programming Interviews in Java.jpg.jpg',
  './images/Starting Out with Java.jpg',
  './images/JavaScript and JQuery.jpg',
  './images/A Tour of C++.jpg',
  './images/C++ in One Hour a Day.jpg',
];
